### ISSUE TITLE
Restructure: Add an order-group that enables running python without any package managers

### ISSUE THREAD

**Issue by arjun024** [paketo-community/python#218]
### Background
See [RFC 0001](https://github.com/paketo-community/python/blob/main/rfcs/0001-restructure.md) that outlines the proposed restructure of python family of buildpacks.  In order to conform to the RFC, a new order-group should be added to the metacnb that enables running python without any package managers.

### Proposal

* Add the following order-group to [python](https://github.com/paketo-community/python/blob/main/buildpack.toml) as the last item in the order:
```
[[order]]

  [[order.group]]
    id = "paketo-community/cpython"

  [[order.group]]
    id = "paketo-community/python-start"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
```

* Add relevant integration tests

**Comment by andymoe** [comment]
Needs acceptance as part of previous process.

**Comment by fg-j** [comment]
@thitch97 or @arjun024 Are we hoping to cut a release of the language family now that this order group is completed?
