### ISSUE TITLE
Restructure: Update order group after pip restructure

### ISSUE THREAD

**Issue by ForestEckhardt** [paketo-community/python#219]
In an effort to fulfill the re-architecture plan laid out in [Python RFC #0001](https://github.com/paketo-community/python/blob/main/rfcs/0001-restructure.md) the Python Buildpack order grouping needs to be updated in the following way.

* Replace the current `pip` order-group of {`python-runtime` + `pip`} with {`cpython` +`pip` + `pip-install` + `python-start` + `procfile`(optional)}

In order to achieve temporary compatibility with non-restructured `pipenv` buildpack:
* Replace the current `pipenv` order-group of {`python-runtime` + `pipenv` + `pip`} with {`cpython` +`pipenv` + `pip` + `pip-install` + `python-start` + `procfile`(optional)}

The `pipenv` group will be modified after it has been restructured to conform with the restructuring RFC.

**Comment by arjun024** [comment]
If a restructured `pipenv` is already released, the temporary `pipenv` modification can be skipped

**Comment by emmjohnson** [comment]
We did not change the pipenv order group because

pipenv still uses python runtime api and not the cpython api
pipenv only produces a requirements.txt during the build phase and cannot satisfy pip-install during detect

**Comment by shanks3012** [comment]
The remaining work has moved to #222 per above comment
