### ISSUE TITLE
Add Python sample apps

### ISSUE THREAD

**Issue by kvedurmu** [paketo-community/python#284]
Could we look into adding sample apps for all supported buildpack configurations in this repo? This would make it easier to share the community buildpack out to users, get feedback, and go through an eventual promotion process.

**Comment by arjun024** [comment]
**Edit**: This documentation should be created in a `samples` directory in this repo. The Python subteam will then have have a much stronger case to ask for promotion to the main Paketo Buildpacks organization. The samples created herein should be in the same format and should be easily movable to https://github.com/paketo-buildpacks/samples
